[Dify]
  enable = true
  api-key = "Key" # Difyçš„API Key
  base-url = "http://DIfyæ¥å£/v1" #Dify APIæ¥å£base url
  commands = ["è€å¤", "dify", "èŠå¤©", "AI"]
  command-tip = """-----XYBot-----
  ğŸ’¬AIèŠå¤©æŒ‡ä»¤ï¼š
  èŠå¤© è¯·æ±‚å†…å®¹
  """
  price = 0
  admin_ignore = true
  whitelist_ignore = true
  http-proxy = ""

  audio-to-text-url = "http://ä½ çš„difyè¯­éŸ³è½¬æ–‡å­—/v1/audio-to-text"
  text-to-audio-url = "http://ä½ çš„difyæ–‡å­—è½¬è¯­éŸ³/v1/text-to-audio"

  robot-names = ["æ¯›çƒ", "DifyBot", "æ™ºèƒ½åŠ©æ‰‹"]
  voice_reply_all = false #é»˜è®¤false
