[Dify]
  enable = true
  api-key = "app-9hiqqQIi8bZfvmaFc56WPyYH" # Difyçš„API Key
  base-url = "http://192.168.6.19:8080/v1" #Dify APIæ¥å£base url
  commands = ["è€å¤", "dify", "èŠå¤©", "AI"]
  command-tip = """-----XYBot-----
  ğŸ’¬AIèŠå¤©æŒ‡ä»¤ï¼š
  èŠå¤© è¯·æ±‚å†…å®¹
  """
  price = 0
  admin_ignore = true
  whitelist_ignore = true
  http-proxy = ""

  audio-to-text-url = "http://192.168.6.19:8080/v1/audio-to-text"
  text-to-audio-url = "http://192.168.6.19:8080/v1/text-to-audio"

  robot-names = ["æ¯›çƒ", "DifyBot", "æ™ºèƒ½åŠ©æ‰‹"]
  voice_reply_all = false #é»˜è®¤false
