[Dify]
  enable = true
  api-key = "xxxxxx" # Difyçš„API Key
  base-url = "xxxxxx/v1" #Dify APIæ¥å£base url
  commands = ["è€å¤", "dify", "èŠå¤©", "AI"]
  command-tip = """-----XYBot-----
  ğŸ’¬AIèŠå¤©æŒ‡ä»¤ï¼š
  èŠå¤© è¯·æ±‚å†…å®¹
  """
  price = 0
  admin_ignore = true
  whitelist_ignore = true
  http-proxy = ""
  voice_reply_all = false
